services:
  - type: web
    name: cv-bert-analyzer
    env: python
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: gunicorn proyecto_cv.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: proyecto_cv.settings
      - key: DISABLE_CACHE
        value: "true"
    disk:
      mountedPath: /opt/render/project/src
      size: 512
    